### ISSUE TITLE
Console graphics

### ISSUE THREAD

**Issue by rkeeves** [palmarcell/prog2-rpg#2]
I was thinking about the view, more specifically how we can make the GUI, without bringing in overkill stuff like Swing, Javafx etc.

Maybe [Lanterna](https://github.com/mabe02/lanterna) could be used.
I was able to make the [tutorials](https://github.com/mabe02/lanterna/tree/master/docs/tutorial) compile.
It has a really low level API suited to drawing ASCII-art based games, in my opinion.
Below is a sample code. 
It prints a string at a specific line, and from a specific char from the left of the terminal's border to the screen
(e.g. how you can treat the screen like a width * height matrix of characters)
```
textGraphics.putString(2, 1, "Lanterna Tutorial 2 - Press ESC to exit", SGR.BOLD);
// TextGraphics putString(int column, int row, String string, SGR extraModifier, SGR... optionalExtraModifiers);
// params:
// column - which column to put the first char
// row  - which row to put the first char
// string - the string of chars to print
// extraModifier- terminal specific codes like color
terminal.flush();
// flush if underlying impl is buffered
```

I'd like to know:
- if anyone else has a better option in mind
- or if we should postpone UI questions to a later date

**Comment by palmarcell** [comment]
This sounds really cool! Thanks for the suggestion, I really appreciate it! :)

However, at this early stage of the project, I think we should mainly focus on the learned techniques, so we could build a nice application without worrying about the actual GUI.

In my opinion, the main business logic can be implemented without knowing the exact final GUI. We'll try to build the app in a loosely coupled way, so we could always change the input/output handling.

**Comment by rkeeves** [comment]
Fair point!

[Here's a lovely **overkill** example](https://youtu.be/2UKKDofoU7o?t=330) of your view separation design goal's usefulness in the long run.
